{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ao-admin-password
  namespace: {{ .Values.orchestrator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  password: {{ .Values.admin.password | quote }}
{{- end }}
