apiVersion: v1
kind: Secret
metadata:
  name: lightwell-quay-config
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    SUPER_USERS:
      - quayadmin
    FEATURE_USER_CREATION: true
