opencodeImage:
  enabled: true
  namespace: lightwell-images
  name: sdlc-opencode
  gitUrl: https://github.com/rhpds/lw-sdlc-opencode.git
  gitRef: "aad125a"
  tag: sha-aad125a
  dockerfilePath: container/Dockerfile
  contextDir: ""

jobAnsibleImage: quay.io/agnosticd/ee-multicloud:chained-2026-08-05
