apiVersion: v1
kind: ConfigMap
metadata:
  name: sdlc-cluster-config
data:
  CLUSTER_NAME: cluster-dvb52
  KEYCLOAK_URL: https://sso.apps.cluster-dvb52.dyn.redhatworkshops.io
  TPA_URL: https://server-lightwell-tpa.apps.cluster-dvb52.dyn.redhatworkshops.io
  TPA_SBOM_LABEL: sdlc-demo-dvb52-1
  TPA_UPLOADER_USERNAME: lightwell-uploader-dvb52-1
  AAP_CONTROLLER_URL: https://aap-aap.apps.cluster-dvb52.dyn.redhatworkshops.io
  EDA_PROJECT_NAME: "SDLC dvb52-1"
  EDA_PROJECT_SCM_URL: https://github.com/sshaaf/lw-sdlc-opencode.git
  EDA_ACTIVATION_NAME: sdlc-remediation-dvb52-1
  EDA_ORGANIZATION_NAME: user-dvb52-1
  EDA_ORGANIZATION_ID: "0"
  EDA_WEBHOOK_URL: http://sdlc-remediation-dvb52-1.aap.svc.cluster.local:5000/
  EDA_WEBHOOK_ROUTE_URL: https://sdlc-remediation-dvb52-1-aap.apps.cluster-dvb52.dyn.redhatworkshops.io/
  GITLAB_URL: https://gitlab-gitlab.apps.cluster-dvb52.dyn.redhatworkshops.io
  REMEDIATION_APP_GITLAB_PATH: lightwell/lw-demo-help-app-dvb52-1
  GITLAB_WEBHOOK_TARGET_URL: https://sdlc-remediation-dvb52-1-aap.apps.cluster-dvb52.dyn.redhatworkshops.io/
  NEXUS_NAMESPACE: lightwell-nexus-dvb52-1
  NEXUS_URL: https://nexus-lightwell-nexus-dvb52-1.apps.cluster-dvb52.dyn.redhatworkshops.io
  NEXUS_WEBHOOK_REPOSITORIES: redhat-packages-validated-dvb52-1,redhat-packages-remediated-dvb52-1
  OPENCODE_IMAGE: quay.io/sshaaf/sdlc-opencode:sha-59ffb92
