apiVersion: v1
kind: Secret
metadata:
  name: aap-admin-password
  namespace: {{ .Values.aap.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  password: {{ .Values.admin.password }}
